version: '3.3'

services:
  client:
    restart: on-failure
    ports:
      - $PORT_CLIENT:80
    image: 'uwcirg/tb-mobile-app:$API_DOCKER_TAG'
    environment:
      NODE_ENV: development
      URL_API: $URL_API
      URL_CLIENT: $URL_CLIENT
      REACT_APP_CONTACT_LINK: $CONTACT_LINK
      REACT_APP_MESSAGE_API: $URL_MESSAGE_API
      REACT_APP_LANGUAGE: $LANGUAGE
      CHOKIDAR_USEPOLLING: 'true'

  db:
    restart: always
    image: postgres:9.5.18
    volumes:
      - source: postgres-files
        target: /var/lib/postgresql/data
        type: volume


  bucket:
    image: minio/minio
    environment:
      - MINIO_ACCESS_KEY=$MINIO_ACCESS_KEY
      - MINIO_SECRET_KEY=$MINIO_SECRET_KEY
    volumes:
      - source: user-files
        target: /files
        type: volume
    entrypoint: sh
    command: -c 'mkdir -p /files/patient-test-photos && /usr/bin/minio server /files'
    ports: 
       - $PORT_MINIO:9000

  web:
    image: uwcirg/tb-foundation:$API_DOCKER_TAG
    environment:
      - DATA=postgres://postgres:postgres@db
      - PASSWORD
      - PORT=3000
      - RAILS_ENV=$ENVIRONMENT
      - SECRET_KEY_BASE=$SECRET_KEY_BASE
      - URL_API=$URL_API
      - URL_CORS=$URL_CORS
      - URL_MINIO=$URL_MINIO
      - REDIS_URL=redis://redis:$PORT_REDIS/12
      - MINIO_ACCESS_KEY=$MINIO_ACCESS_KEY
      - MINIO_SECRET_KEY=$MINIO_SECRET_KEY
      - RAILS_BASE_PASS=$RAILS_BASE_PASS
      - VAPID_PUBLIC_KEY=$VAPID_PUBLIC_KEY
      - VAPID_PRIVATE_KEY=$VAPID_PRIVATE_KEY
    ports:
      - $PORT_API:3000
    depends_on:
      - redis
      - db
    restart: always

  redis:
    image: redis
    restart: always
    volumes:
      - source: redis-files
        target: /redis/
        type: volume
        
  sidekiq:
    image: uwcirg/tb-foundation:$API_DOCKER_TAG
    command: 'sidekiq'
    environment:
      - DATA=postgres://postgres:postgres@db
      - PASSWORD
      - PORT=3000
      - RAILS_ENV=$ENVIRONMENT
      - SECRET_KEY_BASE=$SECRET_KEY_BASE
      - URL_API=$URL_API
      - URL_CORS=$URL_CORS
      - URL_MINIO=$URL_MINIO
      - REDIS_URL=redis://redis:$PORT_REDIS/12
      - MINIO_ACCESS_KEY=$MINIO_ACCESS_KEY
      - MINIO_SECRET_KEY=$MINIO_SECRET_KEY
      - RAILS_BASE_PASS=$RAILS_BASE_PASS
      - VAPID_PUBLIC_KEY=$VAPID_PUBLIC_KEY
      - VAPID_PRIVATE_KEY=$VAPID_PRIVATE_KEY
    depends_on:
      - redis
      - db


volumes:
    user-files: {}
    redis-files: {}
    postgres-files: {}
