version: '3.3'
services:
  web:
    build: ./
    volumes:
      - source: ./
        target: /foundation/
        type: bind
        read_only: false
  sidekiq: 
    build: ./
    volumes:
      - source: ./
        target: /foundation/
        type: bind
        read_only: false
  client:
    entrypoint: ["echo", "Service foo disabled"]
