---
openapi: 3.0.1
components:
  schemas:
    channel:
      type: object
      properties:
        id:
          type: integer
        title:
          type: string
          example: General Discussion
        subtitle:
          type: string
          nullable: true
        messagesCount:
          type: integer
        isPrivate:
          type: boolean
        updatedAt:
          type: string
          format: date-time
        userId:
          type: integer
          nullable: true
        lastMessageTime:
          type: string
          format: date-time
        userType:
          type: string
          nullable: true
        isSiteChannel:
          type: boolean
    update_patient:
      type: object
      properties:
        phoneNumber:
          type: string
        givenName:
          type: string
        familyName:
          type: string
        treatmentStart:
          type: string
          format: date-time
    patient:
      type: object
      properties:
        givenName:
          type: string
        familyName:
          type: string
        treatmentStart:
          type: string
      required:
      - givenName
      - familyName
    push_notification_status_update:
      type: object
      properties:
        deliveredSuccessfully:
          type: boolean
          example: true
        deliveredAt:
          type: string
          format: date-time
        clicked:
          type: boolean
          example: true
        clickedAt:
          type: string
          format: date-time
    push_subscription_update:
      type: object
      properties:
        pushAuth:
          type: string
          example: fCcSIGV5vYUJVIbzG-DvZA
        pushUrl:
          type: string
          example: https://www.example.com
        pushP256dh:
          type: string
          example: BJD99f2Z04fMPPJEpL8u6oAd3BHnTMxuKfsXT_wP
        pushClientPermission:
          type: string
          example: granted
  securitySchemes:
    cookie_auth:
      type: apiKey
      name: jwt
      in: cookie
info:
  title: API V2
  version: v2
paths:
  "/v2/channels":
    get:
      summary: channels
      tags:
      - Channel
      responses:
        '200':
          description: success
          content:
            application/json:
              schema:
                type: array
                items:
                  "$ref": "#/components/schemas/channel"
  "/patient/{id}/password-reset":
    post:
      summary: Resets a patients password
      tags:
      - Password
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '201':
          description: password reset successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  temporaryPassword:
                    type: string
                required:
                - temporaryPassword
        '401':
          description: password reset unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: integer
                  error:
                    type: string
  "/v2/patient/{id}":
    patch:
      summary: Updates phone number
      tags:
      - Patient
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '201':
          description: patient update successful
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/patient"
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/update_patient"
  "/v2/vapid_public_key":
    get:
      summary: get vapid key
      tags:
      - Notifications
      parameters:
      - name: pushClientPermission
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Successfully fetched vapid public key
        '401':
          description: Not Authorized
  "/v2/user/{id}/push_subscription":
    patch:
      summary: Update user push subcription
      tags:
      - Notifications
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Successfully update push subscription details
        '401':
          description: Not Authorized
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/push_subscription_update"
  "/v2/push_notification_status/{id}":
    patch:
      summary: update push status
      tags:
      - Notifications
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '201':
          description: push notification status update successful
        '401':
          description: Unauthorized to access that users push notification statuses
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/push_notification_status_update"
servers:
- url: http://localhost:5062
  variables:
    defaultHost:
      default: http://localhost:5062
