---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/patients/:patient_id/password-reset":
    post:
      summary: Resets a patients password
      tags:
      - Patient
      responses:
        '200':
          description: password reset
        '422':
          description: invalid request
  "/blogs/{id}":
    get:
      summary: Retrieves a blog
      tags:
      - Blogs
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: blog found
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  title:
                    type: string
                  content:
                    type: string
                required:
                - id
                - title
                - content
            application/xml:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  title:
                    type: string
                  content:
                    type: string
                required:
                - id
                - title
                - content
        '404':
          description: blog not found
        '406':
          description: unsupported accept header
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: www.example.com
