---
openapi: 3.0.1
components:
  schemas:
    channel:
      type: object
      properties:
        id:
          type: integer
        title:
          type: string
          example: General Discussion
        subtitle:
          type: string
        messagesCount:
          type: integer
        isPrivate:
          type: boolean
        updatedAt:
          type: string
          format: date-time
        userId:
          type: integer
        lastMessageTime:
          type: string
          format: date-time
        userType:
          type: string
        isSiteChannel:
          type: boolean
    update_patient:
      type: object
      properties:
        phoneNumber:
          type: string
        givenName:
          type: string
        familyName:
          type: string
        treatmentStart:
          type: string
          format: date-time
    patient:
      type: object
      properties:
        givenName:
          type: string
        familyName:
          type: string
        treatmentStart:
          type: string
      required:
      - givenName
      - familyName
  securitySchemes:
    cookie_auth:
      type: apiKey
      name: jwt
      in: cookie
info:
  title: API V1
  version: v1
paths:
  "/v2/channels":
    get:
      summary: channels
      tags:
      - Channel
      responses:
        '200':
          description: success
          content:
            application/json:
              schema:
                type: array
                items:
                  "$ref": "#/components/schemas/channel"
  "/patient/{id}/password-reset":
    post:
      summary: Resets a patients password
      tags:
      - Password
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '201':
          description: password reset successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  temporaryPassword:
                    type: string
                required:
                - temporaryPassword
        '401':
          description: password reset unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: integer
                  error:
                    type: string
  "/v2/patient/{id}":
    patch:
      summary: Updates phone number
      tags:
      - Patient
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '201':
          description: patient update successful
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/patient"
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/update_patient"
servers:
- url: http://localhost:5062
  variables:
    defaultHost:
      default: http://localhost:5062
